INSERT INTO admin (ADMIN_UUID,ID,ISACTIVE,PASSWORD,ISLOCKED,FAILCOUNT,SUCCESSCOUNT,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'Admin',1,'W6ph5Mm5Pz8GgiULbPgzG37mj9g=',0,0,0,'0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;

INSERT INTO role (ROLE_UUID,ROLE_NAME,ROLE_DESC,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'超级管理员','超级管理员','0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;

INSERT INTO admin_role (ADMINROLE_UUID,ADMIN_UUID,ROLE_UUID,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),(SELECT ADMIN_UUID FROM admin WHERE ID = 'Admin'),(SELECT ROLE_UUID FROM role WHERE ROLE_NAME = '超级管理员'),'0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;

INSERT INTO permission (PERMISSION_UUID,FUNCTION_UUID,ROLE_UUID,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),(SELECT FUNCTION_UUID FROM function WHERE FUNCTION_CODE = 'A001-001'),(SELECT ROLE_UUID FROM role WHERE ROLE_NAME = '超级管理员'),'0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;
INSERT INTO permission (PERMISSION_UUID,FUNCTION_UUID,ROLE_UUID,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),(SELECT FUNCTION_UUID FROM function WHERE FUNCTION_CODE = 'A001-002'),(SELECT ROLE_UUID FROM role WHERE ROLE_NAME = '超级管理员'),'0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;

COMMIT;
