INSERT INTO sequence (SEQUENCE_UUID,SEQNAME,NEXTNUM,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'USERID',1000,'0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;
INSERT INTO sequence (SEQUENCE_UUID,SEQNAME,NEXTNUM,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'MERCHANTID',1,'0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;
INSERT INTO sequence (SEQUENCE_UUID,SEQNAME,NEXTNUM,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'ORDERNO',1,'0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;
INSERT INTO sequence (SEQUENCE_UUID,SEQNAME,NEXTNUM,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'ORDERAFTERSALENO',1,'0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;
INSERT INTO sequence (SEQUENCE_UUID,SEQNAME,NEXTNUM,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'PAYORDERNO',1,'0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;
INSERT INTO sequence (SEQUENCE_UUID,SEQNAME,NEXTNUM,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'MERCHANTAPPLICATIONID',1,'0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;
COMMIT;