INSERT INTO setting (SETTING_UUID,SETTING_NAME,SETTING_VALUE,SETTING_DESC,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'LOGIN_MAX_FAILED_COUNT',10,'登录失败次数上限','0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;
INSERT INTO setting (SETTING_UUID,SETTING_NAME,SETTING_VALUE,SETTING_DESC,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'LOGIN_EXPIRE_DURATION',43200,'登录超时时间','0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;
INSERT INTO setting (SETTING_UUID,SETTING_NAME,SETTING_VALUE,SETTING_DESC,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'IS_IGNORE_LOGIN_VERIFICATION',0,'关闭短信验证码','0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;
INSERT INTO setting (SETTING_UUID,SETTING_NAME,SETTING_VALUE,SETTING_DESC,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'PROFIT_RECRUIT_ENABLED',0,'开启推广分润','0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;
INSERT INTO setting (SETTING_UUID,SETTING_NAME,SETTING_VALUE,SETTING_DESC,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'PROFIT_SALE_ENABLED',0,'开启销售分润','0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;

INSERT INTO setting (SETTING_UUID,SETTING_NAME,SETTING_VALUE,SETTING_DESC,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'ORDER_AUTO_CANCEL',0,'订单多少天不付款自动取消','0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;
INSERT INTO setting (SETTING_UUID,SETTING_NAME,SETTING_VALUE,SETTING_DESC,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'ORDER_AUTO_CONFIRM',0,'订单多少天自动收货','0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;
INSERT INTO setting (SETTING_UUID,SETTING_NAME,SETTING_VALUE,SETTING_DESC,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'ORDER_AUTO_EVALUATE',0,'订单多少天自动评价','0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;
INSERT INTO setting (SETTING_UUID,SETTING_NAME,SETTING_VALUE,SETTING_DESC,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'ORDER_AFTERSALE_PERIOD',3,'订单确认收货后多少天内可以申请售后','0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;
INSERT INTO setting (SETTING_UUID,SETTING_NAME,SETTING_VALUE,SETTING_DESC,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'ORDER_AFTERSALE_PROCESS_PERIOD',3,'订单申请退款多少天内商家不处理系统自动同意退款','0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;

INSERT INTO setting (SETTING_UUID,SETTING_NAME,SETTING_VALUE,SETTING_DESC,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'TAX_RATE',10,'会员提现手续费','0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;
INSERT INTO setting (SETTING_UUID,SETTING_NAME,SETTING_VALUE,SETTING_DESC,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'TAX_RATE_MERCHANT',10,'商家提现手续费','0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;

INSERT INTO setting (SETTING_UUID,SETTING_NAME,SETTING_VALUE,SETTING_DESC,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'WX_SUSCRIBE_MSG_ORDER_PAY','nt6tq4z9YcwVfcPVQyU-lSTTaGvU0YHAN_XUBY3bW0I','订单支付订阅消息','0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;
INSERT INTO setting (SETTING_UUID,SETTING_NAME,SETTING_VALUE,SETTING_DESC,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'WX_SUSCRIBE_MSG_ORDER_DELIVERED','kiOjjLxOrmmJNrdEy1FvMC2KmTDw9X1mFLETRjF4siA','订单发货订阅消息','0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;
INSERT INTO setting (SETTING_UUID,SETTING_NAME,SETTING_VALUE,SETTING_DESC,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'WX_SUSCRIBE_MSG_ORDER_RETURN','C5MZY1fd89PM72PrNn5pMjkHlqUhJcdKWh1WKoVjjDI','订单退款订阅消息','0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;
INSERT INTO setting (SETTING_UUID,SETTING_NAME,SETTING_VALUE,SETTING_DESC,IS_DELETED,DATE_CREATE,CREATE_BY,UPDATE_BY) SELECT UUID(),'WX_SUSCRIBE_MSG_AWARD','QPyC2cuQTH_TZKumqLKjNCiU-4NXbZqDDXp75r5W38A','奖励到账订阅消息','0',CURRENT_TIMESTAMP,'System','System' FROM DUAL;


COMMIT;